prefix rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix aml:<http://iais.fraunhofer.de/aml#>
prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#>
prefix schema:<http://schema.org/>
prefix xsd:<http://www.w3.org/2001/XMLSchema#>

Select *
from named<http://iais.fraunhofer.de/aml#M1.2>
where {?x ?y ?z}
